services:
  docker:
    image: docker:dind
    container_name: dind
    privileged: true
    networks:
      - jenkins
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins_home:/var/jenkins_home:rw
    ports:
      - "2376:2376"
    command: --storage-driver overlay2

  jenkins:
    image: jenkins-image:latest
    #build: ./dockerfiles
    #links:
    #  - "ssh-agent:ssh"
    container_name: jenkins
    restart: on-failure
    networks:
      - jenkins
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    ports:
      - "8080:8080"
      - "50000:50000"
    healthcheck:
      test: ["CMD", "curl", "-f", "-u", "admin:11d308610c0b8145a44ffdb4bc4f9ac651", "http://localhost:8080/login"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - jenkins_home:/var/jenkins_home:rw
      - ./jobs:/var/jenkins_home/jobs:rw
      - jenkins-docker-certs:/certs/client:ro
  #ssh-agent:
  #  image: jenkins/ssh-agent
  #  container_name: ssh-agent

networks:
  jenkins:

volumes:
  jenkins_home:
    name: "jenkins_home_dir"
    labels:
      com.jenkins.description: "Home Dir of Jenkins" 
  jenkins-docker-certs:
    name: "jenkins-certs-mgmt"
    labels:
      com.jenkins.description: "Certs for docker and more. Just check install docs" 