services:
  docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    networks:
      - jenkins
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - ./jenkins_home:/var/jenkins_home # Mounting jenkins data to current directory
    ports:
      - "2376:2376"
    command: --storage-driver overlay2

# Need to see why it does not discover the jenkins file
  jenkins:
    depends_on: [jenkins]
    build: ./dockerfiles
    container_name: jenkins
    restart: on-failure
    networks:
      - jenkins
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home # Mounting jenkins data to current directory
      - jenkins-docker-certs:/certs/client:ro

networks:
  jenkins:

volumes:
  jenkins-docker-certs:
